/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jasbro.gui.pages;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JButton;

import jasbro.Jasbro;
import jasbro.gui.objects.div.MyImage;
import jasbro.gui.pictures.ImageData;
import jasbro.util.ConfigHandler;
import jasbro.util.Settings;

/**
 *
 * @author Azrael
 */
public class MainMenu extends MyImage {
	private ImageData imageData = new ImageData("images/backgrounds/New Game Screen.jpg");
	
	/**
	 * Creates new form MainMenu
	 */
	public MainMenu() {
		setVisible(false);
		initComponents();
		setVisible(true);
		repaint();
		setBackgroundImage(imageData);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setLayout(null);
		
		double width = ConfigHandler.getResolution(Settings.RESOLUTIONWIDTH);
		double height = ConfigHandler.getResolution(Settings.RESOLUTIONHEIGHT);
		int widthRat = (int) (width/1280);
		int heightRat = (int) (height/720);
		int iconSize = (int) (65*width/1280);
		int backHomeBtnWidth = (int) (340*width/1280);
		int backHomeBtnHeight = (int) (85*width/1280);
		
		ImageIcon newgameIcon1 = new ImageIcon("images/buttons/newgame.png");
		Image newgameImage1 = newgameIcon1.getImage().getScaledInstance( backHomeBtnWidth, backHomeBtnHeight,  java.awt.Image.SCALE_SMOOTH ) ;  
		newgameIcon1 = new ImageIcon(newgameImage1);
		
		ImageIcon newgameIcon2 = new ImageIcon("images/buttons/newgame hover.png");
		Image newgameImage2 = newgameIcon2.getImage().getScaledInstance( backHomeBtnWidth, backHomeBtnHeight,  java.awt.Image.SCALE_SMOOTH ) ;  
		newgameIcon2 = new ImageIcon(newgameImage2);
		
		newGameButton = new JButton(newgameIcon1);
		newGameButton.setRolloverIcon(newgameIcon2);
		newGameButton.setPressedIcon(newgameIcon1);
		newGameButton.setBounds((int) (470*width/1280),(int) (280*height/720), backHomeBtnWidth, backHomeBtnHeight);
		newGameButton.setBorderPainted(false); 
		newGameButton.setContentAreaFilled(false); 
		newGameButton.setFocusPainted(false); 
		newGameButton.setOpaque(false);
		add(newGameButton);
		
		ImageIcon continueIcon1 = new ImageIcon("images/buttons/continue.png");
		Image continueImage1 = continueIcon1.getImage().getScaledInstance( backHomeBtnWidth, backHomeBtnHeight,  java.awt.Image.SCALE_SMOOTH ) ;  
		continueIcon1 = new ImageIcon(continueImage1);
		
		ImageIcon continueIcon2 = new ImageIcon("images/buttons/continue hover.png");
		Image continueImage2 = continueIcon2.getImage().getScaledInstance( backHomeBtnWidth, backHomeBtnHeight,  java.awt.Image.SCALE_SMOOTH ) ;  
		continueIcon2 = new ImageIcon(continueImage2);
		
		continueButton = new JButton(continueIcon1);
		continueButton.setRolloverIcon(continueIcon2);
		continueButton.setPressedIcon(continueIcon1);
		continueButton.setBounds((int) (470*width/1280),(int) (400*height/720), backHomeBtnWidth, backHomeBtnHeight);
		continueButton.setBorderPainted(false); 
		continueButton.setContentAreaFilled(false); 
		continueButton.setFocusPainted(false); 
		continueButton.setOpaque(false);
		add(continueButton);
		
		ImageIcon quitIcon1 = new ImageIcon("images/buttons/quit.png");
		Image quitImage1 = quitIcon1.getImage().getScaledInstance( backHomeBtnWidth, backHomeBtnHeight,  java.awt.Image.SCALE_SMOOTH ) ;  
		quitIcon1 = new ImageIcon(quitImage1);
		
		ImageIcon quitIcon2 = new ImageIcon("images/buttons/quit hover.png");
		Image quitImage2 = quitIcon2.getImage().getScaledInstance( backHomeBtnWidth, backHomeBtnHeight,  java.awt.Image.SCALE_SMOOTH ) ;  
		quitIcon2 = new ImageIcon(quitImage2);
		
		quitButton = new JButton(quitIcon1);
		quitButton.setRolloverIcon(quitIcon2);
		quitButton.setPressedIcon(quitIcon1);
		quitButton.setBounds((int) (470*width/1280),(int) (520*height/720), backHomeBtnWidth, backHomeBtnHeight);
		quitButton.setBorderPainted(false); 
		quitButton.setContentAreaFilled(false); 
		quitButton.setFocusPainted(false); 
		quitButton.setOpaque(false);
		add(quitButton);
		
		quitButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				Jasbro.getInstance().getGui().dispose();
			}
		});
		continueButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (Jasbro.getInstance().getData() == null) {
					Jasbro.getInstance().continueLastGame();
				}
				else {
					Jasbro.getInstance().getGui().showHouseManagementScreen();
				}
			}
		});
		newGameButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Jasbro.getInstance().getGui().showStartScreen();
			}
		});
	}// </editor-fold>//GEN-END:initComponents
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton continueButton;
	private javax.swing.JButton newGameButton;
	private javax.swing.JButton quitButton;
	// End of variables declaration//GEN-END:variables
	
	@Override
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
	}
}