package jasbro.util;

public enum Settings {
	SAVESLOTS, AUTOSAVE_INTERVAL, CHEAT_MODE, SANDBOX_MODE, 
	LOLI_IMAGES, BLACK_AND_WHITE_IMAGES, FUTA_ON_MALE_IMAGES, THREE_D_IMAGES,
	COSPLAY,
	USE_SYSTEM_LF, SHOW_NUMBERS_ON_BARS, SHOW_UNAVAILABLE_SCHOOL, HIDEARROWKEYS,SLEEP, SHOWTIMETAKEN,
	PROTAGONISTISPLAYER, TREES, RESOLUTIONHEIGHT, RESOLUTIONWIDTH, TOWNSCREENNEW
}